"""Regenerate result summaries from committed JSON, without rerunning models."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
R = ROOT / 'results'
load = lambda name: json.loads((R / name).read_text())


def write(name, text):
    (ROOT / 'docs' / name).write_text(text.strip() + '\n')


def main():
    audit = load('30_research_audit.json')
    a = load('31_embedding_audit.json')['part_a']
    b = load('20_difficulty.json')['part_b_difficulty_model']
    v = load('18_validation.json')
    c = load('26_why_invisible.json')
    prefix = 'Updated 7 September 2026. Generated by `scripts/render_research_notes.py` from the linked result JSON. Older snapshots and superseded interpretations remain in Git history.\n\n'
    text = '# Difficulty prediction and the embedding audit\n\n' + prefix
    text += '## Embedding comparison\n\n'
    text += f"Experiment 31 reruns experiment 20A on {a['_evaluation']['n']:,} positions from {a['_evaluation']['games']:,} games. PCA and scaling are fitted using training folds only. Five-fold standard deviations are not confidence intervals.\n\n"
    text += '| Predictor | Mean AUC | Fold SD |\n|---|---:|---:|\n'
    for key in ['surface only', 'Maia only', 'engine only', 'embedding only', 'surface + engine + Maia', 'surface + engine + Maia + elo', '...+ EMBEDDING']:
        text += f"| {key} | {a[key]['auc']:.3f} | {a[key]['sd']:.3f} |\n"
    text += '\n| Components | Gain over position-only baseline | Gain over rating-aware baseline |\n|---|---:|---:|\n'
    for n in [2,5,10,20,40]:
        text += f"| {n} | {a['_sweep'][f'position-only baseline + {n}PC']['gain']:+.4f} | {a['_sweep'][f'+ elo + {n}PC']['gain']:+.4f} |\n"
    text += '\nNo width improved the full rating-aware baseline in this run. That is a limited predictive result, not proof that the embedding is redundant. The width sweep is exploratory rather than nested model selection. Original experiment 19 used a weaker baseline and an earlier evaluation, so its reported gain is not directly comparable.\n\n'
    text += f"## Saved full-corpus difficulty model\n\nExperiment 20B uses {audit['n']:,} positions and predicts the original player's exact engine match. Five folds are grouped by repaired source-game ID. AUC is {b['everything cheap']['auc']:.3f}; Brier score is {b['_brier']:.3f}, versus {b['_base_rate']*(1-b['_base_rate']):.3f} for the descriptive full-corpus base-rate reference. These are existing saved results, not a new full-model rerun.\n\n"
    text += '| Predicted exact-match rate | Observed exact-match rate |\n|---|---:|\n'
    for row in b['_calibration']:
        text += f"| {row['predicted']:.1%} | {row['actual']:.1%} |\n"
    text += '\nThe fixed-rating trainer scores and six-rating item curves are full-corpus refits including trainer positions. They are not independent item-response calibration or validated ratings. Game splits do not guarantee player, canonical-board-state or temporal separation. Earlier placeholder-ID evaluation errors and claims about underestimating these positions are superseded.\n\nSources: [`31_embedding_audit.json`](../results/31_embedding_audit.json), [`20_difficulty.json`](../results/20_difficulty.json), [methods](METHODS.md).\n'
    write('FINDINGS_difficulty.md', text)
    write('FINDINGS_validation.md', '# Grouping and concept evidence\n\n' + prefix + f'''On 1,745 selected embeddings, the k=8 silhouette is {v['silhouette_real']['8']:.4f}, against {v['silhouette_null']['8']:.4f} after independently shuffling each dimension. Absolute separation is small. This null destroys correlations, not just potential chess categories.

Resampling stability (mean adjusted Rand index): k=6 {v['stability']['6']['mean_ari']:.3f}; k=8 {v['stability']['8']['mean_ari']:.3f}. Eight groups are a teaching choice, not a discovered natural count. Alternative methods give different partitions and many noise points.

The k=8 external permutation test gives p={v['external_validity']['8']['p_value']:.3f}; k=9 gives p={v['external_validity']['9']['p_value']:.3f}. The p-value is a tail frequency under the tested null, not a probability that a hypothesis is true. Several choices of k were explored without a multiple-comparison correction. Independent validation is needed.

Experiment 07 uses an earlier cached set of 646 selected positions and 400 controls. Twelve motif directions reconstruct the average selected-minus-control direction with R²=0.462. Mean per-position reconstruction is 0.202 versus 0.184 in controls. The residual is not evidence that half the concepts cannot be expressed in chess language.

Experiments 05/05b did not establish transferable sparse directions: none of 30 individual fits generalized; grouped fits scored 1.00 within group and 0.515 held out. The representation, rollouts and evaluation differ from Schut et al. The later groups are an exploratory way to organize practice. No completed controlled study establishes their teaching effectiveness.

Experiment 19's stronger representation interpretation is superseded by the controlled comparison and foldwise PCA audit in [difficulty findings](FINDINGS_difficulty.md).

Sources: [`18_validation.json`](../results/18_validation.json), [`07_composition.json`](../results/07_composition.json), [methods](METHODS.md).
''')
    text = '# Move-feature associations\n\n' + prefix
    text += f"Experiment 26 includes {c['n']:,} positions meeting a common minimum 100cp gap: 5,155 with Maia p_max <=5%, 10,443 intermediate and 2,698 with p_max >=30%. Classification uses only the 7,853 extreme-group positions. Thirty binary features yield AUC {c['auc_logistic']:.3f}, fold SD {c['auc_sd']:.3f}, in five folds grouped by game.\n\n"
    text += '| Feature | At most 5% | Intermediate | At least 30% |\n|---|---:|---:|---:|\n'
    for key in ['offers_material','quiet','deep_retreat','to_rim','is_capture','gives_check','escapes_attack','creates_threat']:
        row=c['enrichment'][key]
        text += f"| {key} | {row['invisible']:.1%} | {row['mid']:.1%} | {row['visible']:.1%} |\n"
    text += '\nThe groups share a threshold, not identical stakes or matched covariates. Their actual exact-match rates are 23.3%, 40.9% and 62.3%; these are associations in different positions, not controlled estimates of why people miss moves. Feature labels derive from Maia probabilities. The classifier itself is linear, but its target depends on a neural model.\n\n'
    text += 'The material-exposure feature is an attack/value proxy; it does not evaluate compensation. The legacy extractor can misclassify en passant because it uses destination occupancy. Quiet moves may lead to forcing tactical sequences. The observed trends do not establish a cognitive mechanism or rule out threshold artefacts.\n\nA stronger next comparison should match or adjust for evaluation gap, absolute position evaluation, phase, player rating, time control and source batch, then validate against real human move-quality outcomes on held-out games. See the [learning protocol](LEARNING_STUDY.md) for the intervention needed to test teaching effectiveness.\n\nSource: [`26_why_invisible.json`](../results/26_why_invisible.json).\n'
    write('FINDINGS_methods.md',text)


if __name__ == '__main__':
    main()
